on:
  workflow_dispatch:
    inputs:
      which:
        type: choice
        description: Which dependents to check
        options:
          - strong
          - most

name: Reverse dependency check

jobs:
  revdep_check:
      runs-on: ${{ matrix.config.os }}
      name: ${{ matrix.config.os }} (${{ matrix.config.r }})

      strategy:
        fail-fast: false
        matrix:
          config:
            - {os: macOS-latest,   r: 'release'}
            - {os: windows-latest, r: 'release'}
            - {os: ubuntu-latest,   r: 'release'}

      steps:
          - uses: actions/checkout@v3
          - uses: r-lib/actions/setup-r@v2
            with:
              r-version: ${{ matrix.config.r }}
              http-user-agent: ${{ matrix.config.http-user-agent }}
              use-public-rspm: true
          - uses: r-lib/actions/setup-r-dependencies@v2
          - name: Reverse check ${{ inputs.which }} dependents
            uses: r-devel/recheck/.github/workflows/recheck.yml@v1
            with:
              which: ${{ inputs.which }}
              subdirectory: '' #if your package is in a git subdir
